### PR TITLE
add Permissions-Policy

### PR DESCRIPTION
**Pull request by WLun001**
close https://github.com/gofiber/helmet/issues/32

### CODE REVIEW

**Comment by WLun001** [comment]
updated to use `HeaderPermissionPolicy` constant from latest release

**Comment by WLun001** [comment]
@ReneWerner87 Good to merge this?

**Comment by ReneWerner87** [comment]
Thx for the contribution. 

Can you add some tests? After that i will merge it.

**Comment by WLun001** [comment]
Not sure how to test secure connection

**Pull request merged**
